### PR TITLE
mcs783x.rb: use our own version methods for interpolation

### PR DESCRIPTION
**Pull request by vitorgalvao**

### CODE REVIEW

**Comment by jawshooah** [comment]
Fixed in caskroom/homebrew-cask@4cc511c995acff945506ae76063a572e0152b61f.

**Comment by jawshooah** [comment]
@vitorgalvao In future, if an open PR requires a change like this that's unrelated to the substance of the PR, we should a separate PR targeting @caskroom's `master` instead of the source branch of the already open one.

**Comment by vitorgalvao** [comment]
Sure thing. I thought it’d be easier for you like this (since it builds on the PR and doesn’t cause conflicts).

**Comment by jawshooah** [comment]
Yeah, if I had seen this before I pushed a fix for the build failure and rebased it wouldn't have been an issue. But since I force-pushed, all the old commits from my branch became part of your PR here, hence the conflicts.

**Pull request closed without merging**
